# Generated by Django 2.0.2 on 2018-07-26 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('authentication', '0005_auto_20180725_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='service.Service'),
        ),
    ]
