# Generated by Django 2.0.2 on 2018-07-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='service.Service'),
        ),
    ]
