# Generated by Django 2.0.2 on 2018-08-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20180726_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'managed': True, 'ordering': ('service_category', 'title', 'price')},
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('title', 'id')},
        ),
    ]
