# Generated by Django 2.0.2 on 2018-07-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180727_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(max_length=100),
        ),
    ]
