# Generated by Django 2.0.2 on 2018-08-02 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'managed': True, 'ordering': ('title',)},
        ),
        migrations.AlterUniqueTogether(
            name='servicecategory',
            unique_together={('title', 'id')},
        ),
    ]
